version: 2

defaults: &defaults
  docker:
    - image: docker:17.05.0-ce-git      

jobs:

  docker-build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: docker build -t dotfilez -t $CIRCLE_SHA1 .
      - run:
          name: tag docker image
          command: docker tag $CIRCLE_SHA1 burdz/private/dotfilez:${CIRCLE_BRANCH}
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: push docker image
          command: docker push burdz/private/dotfilez:${CIRCLE_BRANCH}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - docker-build:
          filters:
            branches:
              only:
                - master
